[package]
name = "exoquant"
version = "0.1.0"
authors = ["Dennis Ranke <dennis.ranke@gmail.com>"]

[dependencies]
rand = "0.3.14"

[dev-dependencies]
lodepng = "0.8.1"
simplesvg = { git = "https://github.com/exoticorn/simplesvg", rev = "02cc30867bbdbfe1089b080b4b06edb92dec99a1" }
